### ISSUE TITLE
TypeError: order must be str, not int

### ISSUE THREAD

**Issue by mr917** [DAguirreAg/STL-to-gif#1]
Hi! 
Thanks for uploading your tool. I've tried to use it, but get following error. 

Loading STL
Creating frames
Traceback (most recent call last):
  File "STL-To-Gif.py", line 241, in <module>
    main(sys.argv[1:])
  File "STL-To-Gif.py", line 232, in main
    createFrames()
  File "STL-To-Gif.py", line 96, in createFrames
    scale = stl_mesh.points.flatten(-1)
TypeError: order must be str, not int

Do you have any idea what I'm doing wrong?

greets 
Martin

**Comment by maribaubna** [comment]
Changing the parameter from -1 to 'C' worked for me.

scale = stl_mesh.points.flatten('C')

**Comment by mr917** [comment]
Worked for me as well! 
Thank you.
